meta_product_name: "Mind the Map"
meta_title: "Mind the Map - The Map in your Head"
meta_description: "Can you locate places on a unlabeled city map?"
meta_image: img_path "cover.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
